CC=g++
CFLAGS=-g -W -Wall
#CFLAGS=-ggdb3
LDFLAGS=
SOURCES_H = $(wildcard ../Source/*/*.h)
SOURCES_HH = $(wildcard ../Source/*/*.hh)

all:
	g++ $(CFLAGS) test.cpp -o test

line:
	@echo "###########################################################"
